version: '3.8'

services:
  bot:
    build: .
    volumes:
      - ./src/data:/app/src/data
    env_file:
      - .env
    restart: always
    init: true
    cap_add:
      - NET_RAW  # Для роботи ping
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./data:/app/data  # Монтуємо папку з даними
    env_file:
      - .env  # Використовуємо наш .env файл